import { Product, Collection, JournalPost } from '../types';

export const FALLBACK_COLLECTIONS: Collection[] = [
  {
    id: 'col-1',
    name: 'The Foundations',
    slug: 'the-foundations',
    description: 'The core permanent collection. 240 GSM Supima cotton engineered for daily wear without deformation.',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1400&q=85',
    heroHeadline: 'TIMELESS CUTS. UNCOMPROMISING WEIGHT.',
    isFeatured: true,
  },
  {
    id: 'col-2',
    name: 'Heavyweight Atelier',
    slug: 'heavyweight-atelier',
    description: '280 GSM dense knit architecture. Clean shoulder drape with substantial presence.',
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=1400&q=85',
    heroHeadline: '280 GSM ARCHITECTURAL DRAPE.',
    isFeatured: true,
  },
  {
    id: 'col-3',
    name: 'Raw & Mineral Dyed',
    slug: 'raw-and-dyed',
    description: 'Low-impact garment washed pigments. Subdued earth tones with velvety hand-feel.',
    image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=1400&q=85',
    heroHeadline: 'ORGANIC COMBED FIBERS & MINERAL WASH.',
    isFeatured: true,
  },
];

const COLORS = {
  teal: { id: 'c-teal', name: 'Deep Teal', slug: 'deep-teal', hexCode: '#0D4F4A' },
  black: { id: 'c-black', name: 'Chalk Black', slug: 'chalk-black', hexCode: '#172B2A' },
  white: { id: 'c-white', name: 'Off White', slug: 'off-white', hexCode: '#F5F4EF' },
  mint: { id: 'c-mint', name: 'Washed Mint', slug: 'washed-mint', hexCode: '#B8E0D2' },
  grey: { id: 'c-grey', name: 'Slate Grey', slug: 'slate-grey', hexCode: '#5C6B69' },
};

const SIZES = [
  { id: 's-xs', name: 'Extra Small', code: 'XS', sortOrder: 1 },
  { id: 's-s', name: 'Small', code: 'S', sortOrder: 2 },
  { id: 's-m', name: 'Medium', code: 'M', sortOrder: 3 },
  { id: 's-l', name: 'Large', code: 'L', sortOrder: 4 },
  { id: 's-xl', name: 'Extra Large', code: 'XL', sortOrder: 5 },
  { id: 's-xxl', name: 'Double Extra Large', code: 'XXL', sortOrder: 6 },
];

function generateVariants(productId: string, price: number, comparePrice: number, colors: any[]) {
  const vars: any[] = [];
  colors.forEach((color) => {
    SIZES.forEach((size) => {
      vars.push({
        id: `var-${productId}-${color.slug}-${size.code}`,
        productId,
        colorId: color.id,
        color,
        sizeId: size.id,
        size,
        sku: `RV-${productId.toUpperCase()}-${color.slug.toUpperCase().slice(0, 3)}-${size.code}`,
        price,
        compareAtPrice: comparePrice,
        stock: size.code === 'M' || size.code === 'L' ? 22 : 12,
      });
    });
  });
  return vars;
}

export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: 'p-1',
    name: 'The Essential Tee',
    slug: 'essential-tee',
    shortDescription: '240 GSM Combed Supima Cotton • Structured Everyday Fit',
    longDescription: 'Crafted from 100% extra-long staple Supima cotton, The Essential Tee redefines the foundational garment. A dense interlock weave provides clean drape without cling, while the reinforced double-rib collar holds its crisp geometry through countless washes.',
    story: 'We spent eighteen months perfecting one thing: the neckline. Most T-shirts fail after five washes because the collar stretches and ripples. The Essential Tee features a proprietary 1x1 double-rib construction with invisible internal binding that preserves architectural shape year after year.',
    price: 1499,
    compareAtPrice: 1899,
    fabricComposition: '100% Combed Long-Staple Supima Cotton',
    gsm: 240,
    fit: 'Structured Regular',
    neckType: 'Reinforced 1x1 Double-Ribbed Crew',
    sleeveType: 'Classic Tapered Sleeve',
    finish: 'Pre-shrunk, bio-polished, zero silicone treatment',
    washCare: 'Machine wash gentle cold (30°C) inside-out. Line dry in shade.',
    origin: 'Tiruppur, India',
    modelHeight: "6'1\" (185 cm)",
    modelSize: 'Wearing size M in Deep Teal',
    craftsmanshipDetails: 'Dense 24-gauge knit, twin-needle clean hem, chain-stitched shoulder taping, heat-pressed inner atelier stamp.',
    status: 'ACTIVE',
    isFeatured: true,
    collectionId: 'col-1',
    collection: FALLBACK_COLLECTIONS[0],
    variants: generateVariants('ess', 1499, 1899, [COLORS.teal, COLORS.black, COLORS.white, COLORS.mint]),
    images: [
      { id: 'img-1', productId: 'p-1', colorId: COLORS.teal.id, url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=85', alt: 'The Essential Tee in Deep Teal', isPrimary: true, sortOrder: 0 },
      { id: 'img-2', productId: 'p-1', colorId: COLORS.teal.id, url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=1200&q=85', alt: 'The Essential Tee Profile', isPrimary: false, sortOrder: 1 },
      { id: 'img-3', productId: 'p-1', colorId: COLORS.black.id, url: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=1200&q=85', alt: 'The Essential Tee in Chalk Black', isPrimary: false, sortOrder: 2 },
      { id: 'img-4', productId: 'p-1', colorId: COLORS.white.id, url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1200&q=85', alt: 'The Essential Tee in Off White', isPrimary: false, sortOrder: 3 },
      { id: 'img-5', productId: 'p-1', colorId: null, url: 'https://images.unsplash.com/photo-1523381294911-8d3cead13475?auto=format&fit=crop&w=1200&q=85', alt: 'Fabric Weave & Stitching Detail Macro', isPrimary: false, sortOrder: 4 },
    ],
    reviews: [
      { id: 'r-1', authorName: 'Vikram S.', rating: 5, title: 'The collar holds like nothing else.', comment: 'Washed this six times already. No rippling around the neck, no fading in the deep teal shade.', isVerifiedPurchase: true, createdAt: '2026-03-01' },
      { id: 'r-2', authorName: 'Rohan K.', rating: 5, title: 'Architectural silhouette that actually flatters.', comment: 'The drape is clean and structured. It doesn’t cling around the waist.', isVerifiedPurchase: true, createdAt: '2026-03-05' },
    ],
  },
  {
    id: 'p-2',
    name: 'The Heavyweight Oversized Tee',
    slug: 'heavyweight-oversized-tee',
    shortDescription: '280 GSM Interlock Dense Knit • Architectural Drop Shoulder',
    longDescription: 'Substantial, architectural, and completely opaque. Cut from 280 GSM dense-knit cotton with dropped shoulders and a wider chest box.',
    story: 'Weight creates silhouette. At 280 GSM, this garment sits between a luxury heavyweight T-shirt and a light sweatshirt.',
    price: 1899,
    compareAtPrice: 2299,
    fabricComposition: '100% Pure Organic Ring-Spun Cotton',
    gsm: 280,
    fit: 'Relaxed Architectural Oversized',
    neckType: '30mm High-Gauge Reinforced Collar',
    sleeveType: 'Elongated Drop-Shoulder Sleeve',
    finish: 'Enzyme carbon-washed for velvet hand-feel',
    washCare: 'Cold wash with like colors. Flat dry recommended.',
    origin: 'Coimbatore, India',
    modelHeight: "6'2\" (188 cm)",
    modelSize: 'Wearing size L in Chalk Black',
    craftsmanshipDetails: '280 GSM heavyweight interlock, drop-needle shoulder line, double-reinforced collar tape.',
    status: 'ACTIVE',
    isFeatured: true,
    collectionId: 'col-2',
    collection: FALLBACK_COLLECTIONS[1],
    variants: generateVariants('hvy', 1899, 2299, [COLORS.black, COLORS.teal, COLORS.grey, COLORS.white]),
    images: [
      { id: 'img-21', productId: 'p-2', colorId: COLORS.black.id, url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1200&q=85', alt: 'Heavyweight Oversized Tee Front', isPrimary: true, sortOrder: 0 },
      { id: 'img-22', productId: 'p-2', colorId: COLORS.teal.id, url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=85', alt: 'Heavyweight Oversized in Deep Teal', isPrimary: false, sortOrder: 1 },
      { id: 'img-23', productId: 'p-2', colorId: COLORS.grey.id, url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=1200&q=85', alt: 'Heavyweight Oversized in Slate Grey', isPrimary: false, sortOrder: 2 },
    ],
    reviews: [
      { id: 'r-21', authorName: 'Sameer P.', rating: 5, title: 'Incredible heft without feeling stiff.', comment: 'The drop shoulder is perfectly executed.', isVerifiedPurchase: true, createdAt: '2026-03-10' },
    ],
  },
  {
    id: 'p-3',
    name: 'The Structured Mock Neck',
    slug: 'structured-mock-neck',
    shortDescription: '260 GSM Tailored Knit • 3.5cm Architectural Collar',
    longDescription: 'An elevated interpretation of the mid-century modern mock neck. Tailored through the torso with an engineered 3.5cm ribbed neckband.',
    story: 'Designed to transition effortlessly from tailored outerwear to minimal solo wear.',
    price: 1999,
    compareAtPrice: 2499,
    fabricComposition: '97% Combed Supima Cotton, 3% Japanese Elastane (Collar)',
    gsm: 260,
    fit: 'Tailored Structured',
    neckType: '35mm Architectural Mock Neck',
    sleeveType: 'Fitted Armhole Clean Sleeve',
    finish: 'Silken bio-polished finish',
    washCare: 'Cold wash. Dry flat.',
    origin: 'Tiruppur, India',
    modelHeight: "6'0\" (183 cm)",
    modelSize: 'Wearing size M in Deep Teal',
    craftsmanshipDetails: 'Form-knitted continuous mock neck, ergonomic armscye stitching.',
    status: 'ACTIVE',
    isFeatured: true,
    collectionId: 'col-1',
    collection: FALLBACK_COLLECTIONS[0],
    variants: generateVariants('mck', 1999, 2499, [COLORS.teal, COLORS.black, COLORS.white]),
    images: [
      { id: 'img-31', productId: 'p-3', colorId: COLORS.teal.id, url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=1200&q=85', alt: 'The Structured Mock Neck', isPrimary: true, sortOrder: 0 },
      { id: 'img-32', productId: 'p-3', colorId: COLORS.black.id, url: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=1200&q=85', alt: 'Structured Mock Neck in Black', isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    id: 'p-4',
    name: 'The Atelier Relaxed Tee',
    slug: 'atelier-relaxed-tee',
    shortDescription: '250 GSM Reverse French Terry • Subdued Box Cut',
    longDescription: 'A study in tactile contrast. Features a silky smooth face exterior with an ultra-fine micro-loop terry interior.',
    story: 'Originally developed as a custom studio piece for our design team.',
    price: 1699,
    compareAtPrice: 2099,
    fabricComposition: '100% Organic Micro-Loop French Terry Cotton',
    gsm: 250,
    fit: 'Relaxed Box Cut',
    neckType: 'Self-Fabric Bound Collar',
    sleeveType: 'Relaxed Mid-Arm Sleeve',
    finish: 'Mineral pigment washed',
    washCare: 'Gentle wash cold. Line dry in shade.',
    origin: 'Tiruppur, India',
    modelHeight: "5'11\" (180 cm)",
    modelSize: 'Wearing size M in Washed Mint',
    craftsmanshipDetails: 'French terry micro-loops, flatlock seam interior.',
    status: 'ACTIVE',
    isFeatured: true,
    collectionId: 'col-3',
    collection: FALLBACK_COLLECTIONS[2],
    variants: generateVariants('rel', 1699, 2099, [COLORS.mint, COLORS.grey, COLORS.white]),
    images: [
      { id: 'img-41', productId: 'p-4', colorId: COLORS.mint.id, url: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=1200&q=85', alt: 'Atelier Relaxed Tee in Washed Mint', isPrimary: true, sortOrder: 0 },
      { id: 'img-42', productId: 'p-4', colorId: COLORS.grey.id, url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1200&q=85', alt: 'Atelier Relaxed Tee in Slate Grey', isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    id: 'p-5',
    name: 'The Minimal Long Sleeve',
    slug: 'minimal-long-sleeve',
    shortDescription: '240 GSM Long-Staple Cotton • Architectural Ribbed Cuffs',
    longDescription: 'Engineered for trans-seasonal layering. Clean proportions with 6cm elongated ribbed cuffs.',
    story: 'Long sleeves often bunch awkwardly. We developed an anatomical arm taper with high-recovery ribbing.',
    price: 1799,
    compareAtPrice: 2199,
    fabricComposition: '100% Combed Long-Staple Cotton',
    gsm: 240,
    fit: 'Regular Tailored Fit',
    neckType: 'Double-Rib Crew Collar',
    sleeveType: 'Long Sleeve with 6cm Ribbed Cuff',
    finish: 'Pre-shrunk, bio-washed',
    washCare: 'Machine wash cold.',
    origin: 'Tiruppur, India',
    modelHeight: "6'1\" (185 cm)",
    modelSize: 'Wearing size L in Deep Teal',
    craftsmanshipDetails: 'Seamless tubular torso knitting, twin-needle coverstitch cuffs.',
    status: 'ACTIVE',
    isFeatured: false,
    collectionId: 'col-1',
    collection: FALLBACK_COLLECTIONS[0],
    variants: generateVariants('lng', 1799, 2199, [COLORS.teal, COLORS.black, COLORS.grey]),
    images: [
      { id: 'img-51', productId: 'p-5', colorId: COLORS.teal.id, url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=1200&q=85', alt: 'Minimal Long Sleeve in Deep Teal', isPrimary: true, sortOrder: 0 },
    ],
  },
];

export const FALLBACK_JOURNAL: JournalPost[] = [
  {
    id: 'j-1',
    title: 'UNDERSTANDING GSM: WHY WEIGHT DEFINES DRAPE',
    slug: 'understanding-gsm-why-weight-defines-drape',
    excerpt: 'Grams per square meter (GSM) is the single most defining metric in garment architecture. Here is how weight dictates posture, opacity, and endurance.',
    content: `In standard retail fashion, T-shirts typically hover between 140 and 180 GSM. At this threshold, cotton is thin, prone to twisting along side seams, and easily sheer under direct daylight.\n\nAt Ravetto, we begin at 240 GSM. A heavyweight knit is not merely warmer; it possesses structural rigidity. The fabric hangs away from the torso, creating clean vertical lines and obscuring anatomical contours for a flattering, architectural drape.\n\nWhen you move from 240 GSM to our 280 GSM Interlock knit, the garment takes on sculptural presence. It moves with deliberate cadence rather than fluttering in the wind. That is quiet confidence made tactile.`,
    readTime: '4 min read',
    coverImage: 'https://images.unsplash.com/photo-1523381294911-8d3cead13475?auto=format&fit=crop&w=1200&q=85',
    author: 'Ravetto Atelier',
    publishedAt: '2026-03-01',
  },
  {
    id: 'j-2',
    title: 'THE ANATOMY OF A GOOD T-SHIRT: COLLAR, SEAM, HEM',
    slug: 'the-anatomy-of-a-good-t-shirt',
    excerpt: 'Eighteen months deconstructing collars, twin-needle tensions, and the invisible shoulder tape that protects against hanger stretch.',
    content: `The collar of a T-shirt is the frame of your face. When a collar bacon-rolls after washing, the entire outfit degrades immediately.\n\nOur double-ribbed 1x1 collar is knitted with high-recovery combed cotton wrapped over an internal herringbone stabilizing tape. Even after repeated wash cycles, the neckline remains crisp, sharp, and flat against the clavicle.\n\nDown at the hem, we employ twin-needle coverstitching spaced at 6mm intervals. This distributes tension equally across lateral movements, completely preventing curled edges.`,
    readTime: '5 min read',
    coverImage: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=1200&q=85',
    author: 'Ravetto Atelier',
    publishedAt: '2026-03-04',
  },
  {
    id: 'j-3',
    title: 'BUILDING THE EVERYDAY UNIFORM: THE RESTRAINT OF ESSENTIALS',
    slug: 'building-the-everyday-uniform',
    excerpt: 'Why having fewer, impeccably cut garments liberates daily focus and sharpens personal presence.',
    content: `A wardrobe built on transient logos and novelty cuts is an exhausting cycle. The modern uniform is quiet. It pairs a heavyweight Deep Teal or Chalk Black T-shirt with tailored pleated trousers or raw denim.\n\nWhen the silhouette, the fabric weight, and the finish are refined, you need zero surface ornamentation. The quality of the cotton speaks for itself.`,
    readTime: '3 min read',
    coverImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=85',
    author: 'Ravetto Atelier',
    publishedAt: '2026-03-07',
  },
];
